### ISSUE TITLE
🛠 Tooling: sort `package.json`

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/template-typescript-node-package#223]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-tools/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Keep `package.json` sorted to make it easy to quickly find each section.

### Additional Info

This can automatically be done with a prettier plugin.

**Comment by JoshuaKGoldberg** [comment]
Agreed, `package.json` should be sorted - and it already is! See https://github.com/JoshuaKGoldberg/ts-api-tools/pull/20's https://github.com/JoshuaKGoldberg/ts-api-tools/actions/runs/4107681077/jobs/7089665450:

```plaintext
/home/runner/work/ts-api-tools/ts-api-tools/package.json
Error:   44:4  error  Expected object keys to be in ascending order. 'import' should be before 'types'  jsonc/sort-keys
Error:   54:2  error  Expected object keys to be in ascending order. 'name' should be before 'types'    jsonc/sort-keys
```

The difference is, I have them sorted in alphabetical order. Which is something I believe in - it's hard to memorize arbitrary sorts for different systems. Alphabetical is a nice predictable standard. What do you think?

Btw, I transferred this issue over from `ts-api-tools` to this `template-typescript-node-package` since it impacts all of them.

**Comment by JoshuaKGoldberg** [comment]
aside: @allcontributors add @RebeccaStevens for idea

**Comment by JoshuaKGoldberg** [comment]
All right, I filed https://github.com/ota-meshi/eslint-plugin-jsonc/issues/211. The alphabetical ordering feels _wrong_ to me... but so did a lot of good tooling things, such as Prettier. So maybe I'm just being a luddite. Let's try it out!
